version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

workflows:
  version: 2
  test:
    jobs:
      - py36
      - py37
      - flake8
      - black
      - mypy
      - check-manifest
      - docs
      - doctest
      - pydocstyle

jobs:
  py37: &test-template
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: sudo pip install tox || pip install tox
      - restore_cache:
          name: Restoring tox cache
          keys:
            - tox-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}
            - tox-v1-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Run tests
          command: |
            tox -e $CIRCLE_JOB -- \
              --junit-xml=test-results/pytest/results.xml \
              --cov-report=xml
      - save_cache:
          name: Saving tox cache
          key: tox-v1-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}
          paths:
            - ./.tox
            - ~/.cache/pip
      - codecov/upload:
          file: coverage.xml
      - store_test_results:
          path: test-results

  py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  flake8: *test-template

  black: *test-template

  mypy: *test-template

  check-manifest: *test-template

  docs: *test-template

  doctest: *test-template

  pydocstyle: *test-template
